### ISSUE TITLE
Unsupported dot-star suffix (.*) in until-build version

### ISSUE THREAD

**Issue by mmakos** [brian-mcnamara/plugin_uploader#17]
Hi,
According to [IntelliJ docummentation](https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html) it is possible to define version with dot-star "to support all releases for the specific branch". But since plugin uploader version **1.2.0** it is not supported.
During conversion to `BuildNumber` and back to `String`, the asterisk is lost. So instead of `233.*` i get `233.` in my XML file, and my plugin is not available on any IntelliJ version with 233 build.

Is it possible to do something like this in `BuildNumber#aaString` method?
```
for (int each : myComponents) {
  builder.append(each != SNAPSHOT_VALUE ? each : STAR)
         .append('.');
}
```

**Comment by brian-mcnamara** [comment]
Sorry about the delay, I somehow missed this notification in my inbox. Ill take a look at this over the weekend.

**Comment by brian-mcnamara** [comment]
I was torn between returning `*` back, or whether it return Integer.MAX_VALUE. There are other cases where the plugin uses MAX_VALUE when auto updating a previous build when a new version has a later until build, but I believe both will be treated the same, and `*` is a bit nicer then a large number. I may want to reevaluate the auto update logic and determine whether I should use * instead... 

Either way, I have updated the logic as you suggested, and ran some tests to make sure it all would work.
