### ISSUE TITLE
Compatibility with Artifactory

### ISSUE THREAD

**Issue by pcdv** [brian-mcnamara/plugin_uploader#2]
Hi,

Thanks for sharing your Gradle plugin!

I tried to use it to publish an IntelliJ plugin to a private Artifactory instance but the upload failed with error 405.

Artifactory (or at least the old version I have: 3.4.2) only accepts PUT and not POST.

**Maybe a property to use PUT instead of POST could be helpful?**

Anyway I was able to upload my plugin using a shellscript (and curl) so this is not a big issue.

Cheers

**Comment by brian-mcnamara** [comment]
Thanks for raising this! I did grab the OS artifactory and set it up to confirm. Looks like it is simply changing POST to PUT. I have added a uploadMethod parameter like you mentioned and will be released today as version 1.1.1
