### ISSUE TITLE
Absolute download URLs

### ISSUE THREAD

**Issue by mkw** [brian-mcnamara/plugin_uploader#7]
We use a URL shortener to let IDEA point to our nexus repository as an enterprise plugin repo w/o a long path. IDEA uses the wrong base when trying to download -- i.e.:

* Shortened URL: `https://shortlink.example.com/jb-repo`
* Actual URL to which we 301: `https://mynexus.example.com/repository/repo/updatePlugins.xml` (has to point directly to upatePlugins for IDEA to find it).
* Current XML fragment in updatePlugins.xml: `<plugin id="com.example.my-plugin" url="./My%20Plugin/my-plugin-0.0.1.zip" version="0.0.1">`
* IDEA resolves as: `https://shortlink.example.com/My%20Plugin/my-plugin-0.0.1.zip` instead of `https://mynexus.example.com/repository/repo/My%20Plugin/my-plugin-0.0.1.zip`
* Required XML fragment: `<plugin id="com.example.my-plugin" url="https://mynexus.example.com/repository/repo/My%20Plugin/my-plugin-0.0.1.zip" version="0.0.1">`

I'm proposing that a property is added called `absoluateDownloadUrls` that constructs download URLs as absolute URLs instead of the relative `./` and will have a PR shortly.

**Comment by brian-mcnamara** [comment]
Makes sense to me. 
One thing to note is this does limit the use of mirrors, but since you are using a short link it sounds like either a router is in front of nexus or there is only one node.
Another thing to think about is whether the tooling should set the option (absoluteDownloadUrl) to true if other plugin entries use absolute paths in the update xml file.

**Comment by mkw** [comment]
Yea -- it's definitely hackish -- I also considered making the absolute download prefix a String to semi-solve some of this. But in the end decided simple was better for now. If you want to do something else in the long run, I'll adapt our use; what we have is a bit of a hack. :(

**Comment by brian-mcnamara** [comment]
I thought of that too, but I could not come up with a reason to publish with one url and have the download be at a different path. Either way, I think the boolean is fine since I can see the need. Either way 1.2.3 is published with this change so hopefully the plugin can be used for your need :)
